all:
	@echo "Please select a sub-command"
dev: frontend
frontend:
	@echo "Making frontend dev server..."
	@cd galeri/ && npm run start
build:
	@echo "Building frontend..."
	cd galeri/ && npm run build

